name: Pylint Flask Application for Raspberry

on:
  push:
    branches: [ master ]
    paths:
      - raspberry/**
  pull_request:
    branches: [ master ]
    paths:
      - raspberry/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Pylint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    defaults:
      run:
        working-directory: raspberry

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
